name: train_menu_creator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  go_router: ^14.8.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  flutter_dotenv: ^5.2.1
  riverpod_annotation: ^2.6.1
  dev: ^1.0.0
  http: ^1.4.0
  uuid: ^4.5.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  fl_chart: ^1.0.0
  url_launcher: ^6.3.1
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.6
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4


flutter:
  uses-material-design: true
  assets:
    - .env